package tryAndCatch;

public class EceptionIntro
{
//	Exception:
//		During the execution of java program, JVM faces the abnormal situations based
//      on the code declaration.
	
//		If the JVM faces the abnormal situations then, JVM triggers an event, this 
//      event is known as Exception.
	
//		If exception event got generated in the java program then it results in the 
//      termination of the java program.
	
//		If the termination of the java program takes place then the code is considered
//      to be non- feasible code for the execution.
	
//		If any event is generated by the JVM then the program need to handle the event
//       so that all the lines present in the program gets executed.
	
	public static void main(String[] args)
	{
		int a=10;
		int b=0;
		int c=a/b;
		System.out.println(c);
		
		//op==>ArithmeticException: / by zero
		
//		Exception Handling: Handling the event generated by JVM during program 
//      execution is known as Exception handling.
//		It is recommended to handle events during execution flow only. 
//		
		
//		Syntax:
//            try{
//                  //risky code  
//              }
//             catch(event/exceptionName refVariable){
//                         //event handled message
//              }


		
	}


}
